---
- name: Base system configuration for HPC cluster
  hosts: cluster
  become: yes
  vars:
    cluster_user: "clusteradmin"
    timezone: "UTC"

  tasks:
    - name: Update package cache
      dnf:
        update_cache: yes

    - name: Install base packages
      dnf:
        name:
          - git
          - curl
          - wget
          - vim
          - tree
          - net-tools
          - bind-utils
          - nftables
          - chrony
          - nfs-utils
          - openssh-server
          - sudo
          - python3
          - python3-pip
        state: present

    - name: Create cluster user
      user:
        name: "{{ cluster_user }}"
        state: present
        groups: wheel
        append: yes

    - name: Configure sudo for cluster user
      copy:
        content: "{{ cluster_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ cluster_user }}"
        mode: '0440'

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Enable and start chronyd
      systemd:
        name: chronyd
        enabled: yes
        state: started

    - name: Enable and start sshd
      systemd:
        name: sshd
        enabled: yes
        state: started

    - name: Disable and stop firewalld
      systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: Enable and start nftables
      systemd:
        name: nftables
        enabled: yes
        state: started
