---
- name: Verify cluster configuration
  hosts: cluster
  become: yes

  tasks:
    - name: Check system information
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel: {{ ansible_kernel }}

    - name: Check service status
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - sshd
        - chronyd
        - nftables

    - name: Verify NFS mount on compute nodes
      stat:
        path: /home
      register: nfs_mount
      when: "'compute' in group_names"

    - name: Display NFS mount status
      debug:
        msg: "NFS mount point /home exists: {{ nfs_mount.stat.exists }}"
      when: "'compute' in group_names"

    - name: Test SSH connectivity
      shell: |
        ssh -o ConnectTimeout=5 {{ cluster_user }}@{{ item }} "hostname"
      loop: "{{ groups.cluster }}"
      register: ssh_results
      changed_when: false
      ignore_errors: yes
      become_user: "{{ cluster_user }}"

    - name: Display SSH connectivity results
      debug:
        msg: "SSH to {{ item.item }}: {{ 'SUCCESS' if item.rc == 0 else 'FAILED' }}"
      loop: "{{ ssh_results.results }}"
