---
all:
  vars:
    ansible_user: clusteradmin
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    cluster_user: clusteradmin
    head_node_ip: 10.242.64.4
    nfs_export_path: /home
    timezone: "UTC"
    cluster_network: "10.242.64.0/24"
    nfs_server: "10.242.64.4"  # Use IP instead of hostname
    mount_point: "/home"

  children:
    head_node:
      hosts:
        head:
          ansible_host: 10.242.64.4
          node_type: head

    compute:
      hosts:
        com1:
          ansible_host: 10.242.64.5
          node_type: compute
        com2:
          ansible_host: 10.242.64.6
          node_type: compute
        com3:
          ansible_host: 10.242.64.26
          node_type: compute

    cluster:  # All nodes group
      hosts:
        head:
        com1:
        com2:
        com3:
