---
- name: Fix broken environment variables
  hosts: cluster
  become: yes

  tasks:
    - name: Remove problematic environment variables
      lineinfile:
        path: /etc/environment
        regexp: "^{{ item }}"
        state: absent
      loop:
        - "PATH=/usr/lib64/openmpi/bin:$PATH"
        - "LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH"
        - "MANPATH=/usr/lib64/openmpi/share/man:$MANPATH"

    - name: Remove problematic profile file
      file:
        path: /etc/profile.d/hpc-environment.sh
        state: absent

    - name: Set proper environment variables for MPI users only
      copy:
        content: |
          # HPC Environment - Load MPI modules when needed
          if [ -d "/usr/lib64/openmpi" ]; then
            export PATH=/usr/lib64/openmpi/bin:$PATH
            export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
            export MANPATH=/usr/lib64/openmpi/share/man:$MANPATH
          fi
        dest: "/etc/profile.d/mpi-environment.sh"
        mode: '0644'
