- name: Install NFS server packages
  dnf:
    name: nfs-utils
    state: present

- name: Configure NFS exports
  copy:
    content: "{{ nfs_export_path }} {{ cluster_network }}(rw,async,no_subtree_check,no_root_squash)"
    dest: /etc/exports

- name: Create NFS export directory
  file:
    path: "{{ nfs_export_path }}"
    state: directory
    mode: '0755'

- name: Enable and start NFS server
  systemd:
    name: nfs-server
    enabled: yes
    state: started

- name: Export NFS shares
  command: exportfs -ra
