- name: Configure chrony based on node type
  block:
    - name: Configure chrony as NTP server (head node)
      copy:
        content: |
          pool 2.rhel.pool.ntp.org iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          allow 10.242.64.0/24
          local stratum 10
          keyfile /etc/chrony.keys
          leapsectz right/UTC
          logdir /var/log/chrony
        dest: /etc/chrony.conf
        backup: yes
      when: "'head_node' in group_names"

    - name: Configure chrony as NTP client (compute nodes)
      copy:
        content: |
          server head iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          keyfile /etc/chrony.keys
          leapsectz right/UTC
          logdir /var/log/chrony
        dest: /etc/chrony.conf
        backup: yes
      when: "'compute' in group_names"

- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted

- name: Wait for NTP synchronization
  command: chronyc waitsync 10
  register: ntp_sync
  until: ntp_sync.rc == 0
  retries: 10
  delay: 5
  ignore_errors: yes
