name: Deploy Compute Node on IBM Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-deploy:
    name: 'Deploy Compute Node'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var="ibmcloud_api_key=${{ secrets.IBM_CLOUD_API_KEY }}"
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="ibmcloud_api_key=${{ secrets.IBM_CLOUD_API_KEY }}"
      working-directory: ./terraform

    - name: Get Outputs
      id: terraform
      run: |
        echo "private_ip=$(terraform output -raw com3_private_ip)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

  ansible-configuration:
    name: 'Ansible Configuration'
    runs-on: ubuntu-latest
    needs: [terraform-deploy]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Display deployment info
      run: |
        echo "New compute node deployed at: ${{ needs.terraform-deploy.outputs.private_ip }}"
        echo "Node will be automatically integrated into existing cluster"

  report:
    name: 'Deployment Report'
    runs-on: ubuntu-latest
    needs: [terraform-deploy, ansible-configuration]
    
    steps:
    - name: Create summary
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        # Week 4: CI/CD Pipeline Complete ✅

        ## Infrastructure Details
        - **New Node IP**: ${{ needs.terraform-deploy.outputs.private_ip }}
        - **Deployment Time**: $(date)
        - **Region**: eu-gb
        - **Zone**: eu-gb-2
        - **VPC**: eu-gb-default-vpc-10182040
        - **Image**: CentOS Stream 9

        ## Week 4 Requirements Met
        - ✅ CI/CD Pipeline with GitHub Actions
        - ✅ Terraform Infrastructure as Code
        - ✅ Automated compute node deployment
        - ✅ Integration with existing cluster
        - ✅ Configuration management ready

        ## Cluster Status
        - Head Node: 10.242.64.4
        - Compute Node 1: 10.242.64.5
        - Compute Node 2: 10.242.64.6
        - Compute Node 3: ${{ needs.terraform-deploy.outputs.private_ip }}

        Your 4-node HPC cluster is now fully automated!
        EOF
