name: Deploy COM3 Node

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup SSH for head node access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="ibmcloud_api_key=${{ secrets.IBM_CLOUD_API_KEY }}"

    - name: Wait for com3 to be ready
      run: |
        sleep 60

    - name: Get com3 IP
      id: terraform
      run: |
        cd terraform
        terraform output com3_private_ip > ip.txt
        COM3_IP=$(grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' ip.txt | head -1)
        echo "COM3_IP=$COM3_IP" >> $GITHUB_ENV
        echo "Com3 IP: $COM3_IP"

    - name: Configure com3 via head node
      run: |
        echo "Configuring com3 at $COM3_IP via head node"
        
        # SSH to head node, then from there SSH to com3 (since head can reach private IPs)
        ssh -o StrictHostKeyChecking=no clusteradmin@141.125.159.109 << 'HEAD_SCRIPT'
          echo "Connected to head node, now configuring com3 at $COM3_IP"
          
          # STEP 1: Login to com3 as root and create user
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@$COM3_IP "adduser clusteradmin"
          
          # STEP 2: Set password
          ssh -o StrictHostKeyChecking=no root@$COM3_IP "echo '!Super@4' | passwd --stdin clusteradmin"
          
          # STEP 3: Setup sudo access
          ssh -o StrictHostKeyChecking=no root@$COM3_IP "echo 'clusteradmin ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/clusteradmin"
          ssh -o StrictHostKeyChecking=no root@$COM3_IP "chmod 440 /etc/sudoers.d/clusteradmin"
          
          echo "User setup complete on com3"
HEAD_SCRIPT

    - name: Setup NFS on com3 via head node
      run: |
        echo "Setting up NFS on com3 at $COM3_IP via head node"
        
        ssh -o StrictHostKeyChecking=no clusteradmin@141.125.159.109 << 'NFS_SCRIPT'
          echo "Setting up NFS on com3 at $COM3_IP"
          
          # Login to com3 as clusteradmin and run the exact commands
          ssh -o StrictHostKeyChecking=no clusteradmin@$COM3_IP "sudo dnf install nfs-utils -y"
          ssh -o StrictHostKeyChecking=no clusteradmin@$COM3_IP "cd / && sudo mount -t nfs head:/home /home"
          ssh -o StrictHostKeyChecking=no clusteradmin@$COM3_IP "cd ~ && sudo setsebool -P use_nfs_home_dirs 1"
          
          echo "NFS setup complete on com3"
NFS_SCRIPT

    - name: Verify setup via head node
      run: |
        echo "Verifying setup on com3 at $COM3_IP via head node"
        
        ssh -o StrictHostKeyChecking=no clusteradmin@141.125.159.109 << 'VERIFY_SCRIPT'
          echo "Verifying com3 setup at $COM3_IP"
          
          ssh -o StrictHostKeyChecking=no clusteradmin@$COM3_IP "id && echo '✓ Logged in as clusteradmin'"
          ssh -o StrictHostKeyChecking=no clusteradmin@$COM3_IP "mount | grep nfs && echo '✓ NFS mounted'"
          ssh -o StrictHostKeyChecking=no clusteradmin@$COM3_IP "sudo -l | head -5 && echo '✓ Sudo access working'"
          
          echo "Verification complete"
VERIFY_SCRIPT

    - name: Display completion message
      run: |
        echo "=========================================="
        echo "✅ COM3 DEPLOYMENT COMPLETE"
        echo "=========================================="
        echo "com3 node: $COM3_IP"
        echo "User: clusteradmin"
        echo "Password: !Super@4"
        echo "NFS: Mounted /home from head node"
        echo ""
        echo "To connect: ssh clusteradmin@141.125.159.109 then ssh clusteradmin@$COM3_IP"
        echo "=========================================="
