name: Deploy COM3 Node

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="ibmcloud_api_key=${{ secrets.IBM_CLOUD_API_KEY }}"

    - name: Wait for com3 to be ready
      run: |
        sleep 60

    - name: Get com3 IP
      id: terraform
      run: |
        cd terraform
        terraform output com3_private_ip > ip.txt
        COM3_IP=$(grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' ip.txt | head -1)
        echo "COM3_IP=$COM3_IP" >> $GITHUB_ENV
        echo "Com3 Private IP: $COM3_IP"

    - name: Display manual instructions
      run: |
        echo "=========================================="
        echo "✅ COM3 INSTANCE CREATED"
        echo "=========================================="
        echo "com3 node (Private): $COM3_IP"
        echo ""
        echo "MANUAL STEP REQUIRED:"
        echo "1. Go to IBM Cloud Console"
        echo "2. Find the floating IP: 141.125.157.5"
        echo "3. Bind it to the new com3 instance"
        echo "4. After binding, run these commands:"
        echo ""
        echo "First, as root:"
        echo "ssh root@141.125.157.5"
        echo "adduser clusteradmin"
        echo "echo '!Super@4' | passwd --stdin clusteradmin"
        echo "echo 'clusteradmin ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/clusteradmin"
        echo "chmod 440 /etc/sudoers.d/clusteradmin"
        echo "exit"
        echo ""
        echo "Then, as clusteradmin:"
        echo "ssh clusteradmin@141.125.157.5"
        echo "sudo dnf install nfs-utils -y"
        echo "cd / && sudo mount -t nfs head:/home /home"
        echo "cd ~ && sudo setsebool -P use_nfs_home_dirs 1"
        echo ""
        echo "To verify:"
        echo "ssh clusteradmin@141.125.157.5"
        echo "id"
        echo "mount | grep nfs"
        echo "sudo -l"
        echo "=========================================="
