name: Deploy Compute Node on IBM Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-deploy:
    name: 'Deploy Compute Node'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var="ibmcloud_api_key=${{ secrets.IBM_CLOUD_API_KEY }}"
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="ibmcloud_api_key=${{ secrets.IBM_CLOUD_API_KEY }}"
      working-directory: ./terraform

    - name: Get Outputs
      id: terraform
      run: |
        echo "private_ip=$(terraform output -raw com3_private_ip)" >> $GITHUB_OUTPUT
        echo "public_ip=$(terraform output -raw com3_public_ip)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

  report:
    name: 'Deployment Report'
    runs-on: ubuntu-latest
    needs: [terraform-deploy]
    
    steps:
    - name: Create summary
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        # Compute Node Deployment Complete ✅
        - **New Node Private IP**: ${{ needs.terraform-deploy.outputs.private_ip }}
        - **New Node Public IP**: ${{ needs.terraform-deploy.outputs.public_ip }}
        - **Deployment Time**: $(date)
        - **Region**: eu-gb
        EOF
