name: Deploy and Configure Compute Node on IBM Cloud

on:
  push:
    branches: [ main ]
    paths: [ 'terraform/**', 'ansible/**' ]
  workflow_dispatch:
    inputs:
      node_name:
        description: 'Compute node name'
        required: true
        default: 'com2'

jobs:
  terraform-deploy:
    name: 'Terraform Infrastructure Deployment'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.5.0'

    - name: Terraform Format
      run: terraform fmt
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      env:
        TF_VAR_ibmcloud_api_key: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform
      env:
        TF_VAR_ibmcloud_api_key: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      env:
        TF_VAR_ibmcloud_api_key: ${{ secrets.IBM_CLOUD_API_KEY }}

    - name: Get Terraform Outputs
      id: terraform
      run: |
        echo "instance_id=$(terraform output -raw com2_instance_id)" >> $GITHUB_OUTPUT
        echo "private_ip=$(terraform output -raw com2_private_ip)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Update Ansible Inventory
      run: |
        NEW_IP=${{ steps.terraform.outputs.private_ip }}
        NODE_NAME=${{ github.event.inputs.node_name || 'com2' }}
        
        # Update inventory file with new node
        cat > ansible/inventory.yml << EOF
        ---
        all:
          vars:
            ansible_user: clusteradmin
            ansible_ssh_private_key_file: ~/.ssh/id_ed25519
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
            cluster_user: clusteradmin
            head_node_ip: 10.242.64.4
            nfs_export_path: /home

          children:
            head:
              hosts:
                head:
                  ansible_host: 10.242.64.4
                  node_type: head

            compute:
              hosts:
                com1:
                  ansible_host: 10.242.64.5
                  node_type: compute
                $NODE_NAME:
                  ansible_host: $NEW_IP
                  node_type: compute

            cluster:
              hosts:
                head:
                com1:
                $NODE_NAME:
        EOF
        
        echo "Updated inventory with new node: $NODE_NAME ($NEW_IP)"

    - name: Upload Terraform Outputs
      uses: actions/upload-artifact@v4
      with:
        name: terraform-outputs
        path: |
          terraform/.terraform
          terraform/terraform.tfstate
        retention-days: 1

  ansible-configuration:
    name: 'Ansible Configuration Management'
    runs-on: ubuntu-latest
    needs: terraform-deploy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Terraform Outputs
      uses: actions/download-artifact@v4
      with:
        name: terraform-outputs
        path: terraform/

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Display Ansible version
      run: ansible --version

    - name: Create SSH key for GitHub Actions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Add head node to known hosts
        ssh-keyscan -H 141.125.159.109 >> ~/.ssh/known_hosts

    - name: Wait for new node to be accessible via SSH
      run: |
        NEW_IP=${{ needs.terraform-deploy.outputs.private_ip }}
        echo "Waiting for node $NEW_IP to be SSH accessible..."
        
        until ssh -i ~/.ssh/id_ed25519 -o ConnectTimeout=5 -o StrictHostKeyChecking=no clusteradmin@$NEW_IP "echo 'Node is up'"; do
          echo "Node not ready yet, waiting 30 seconds..."
          sleep 30
        done
        echo "Node $NEW_IP is now accessible via SSH"

    - name: Run base system configuration
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/base-setup.yml

    - name: Run network configuration
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/network-setup.yml

    - name: Run NFS configuration
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/nfs-setup.yml

    - name: Run NTP configuration
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/ntp-setup.yml

    - name: Run SSH configuration
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/ssh-setup.yml

    - name: Run HPC software installation
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/hpc-software.yml

    - name: Verify cluster configuration
      run: |
        cd ansible
        ansible-playbook -i inventory.yml playbooks/verify-cluster.yml

    - name: Upload configuration logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ansible-logs
        path: |
          ansible/*.retry
        retention-days: 7

  final-report:
    name: 'Generate Deployment Report'
    runs-on: ubuntu-latest
    needs: [terraform-deploy, ansible-configuration]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create deployment summary
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        # IBM Cloud Cluster Deployment Complete ✅

        ## Infrastructure Details
        - **New Node**: ${{ needs.terraform-deploy.outputs.private_ip }}
        - **Instance ID**: ${{ needs.terraform-deploy.outputs.instance_id }}
        - **Deployment Time**: $(date)

        ## Configuration Applied
        - ✅ Base system configuration
        - ✅ Network setup
        - ✅ NFS shared storage
        - ✅ NTP time synchronization
        - ✅ Passwordless SSH
        - ✅ HPC software stack
        - ✅ Cluster verification

        ## Next Steps
        1. SSH to head node: \`ssh clusteradmin@141.125.159.109\`
        2. Verify cluster: \`ssh com2 hostname\`
        3. Check NFS: \`ls /home\` on compute nodes

        ## Cost Information
        - Monthly cost for 3-node cluster: ~$254
        - Remaining credit: Monitor via IBM Cloud Console
        EOF
